### ISSUE TITLE
Canvas rotation breaks the display of non-square pixels

### ISSUE THREAD

**Issue by swederik** [chafey/cornerstone#18]
The size of the pixels is not changed when the canvas is rotated. Here's an example using a T1-weighted MRI resampled to have (extremely) anisotropic voxels.

Before:

![screen shot 2015-05-20 at 10 03 05](https://cloud.githubusercontent.com/assets/607793/7721389/83b333d8-fed7-11e4-87b1-b953eb26ce57.png)

After rotation counter-clockwise by 90 degrees:

![screen shot 2015-05-20 at 10 03 24](https://cloud.githubusercontent.com/assets/607793/7721397/920975e6-fed7-11e4-91af-7ff52610bcff.png)

**Comment by chafey** [comment]
I think this is now fixed in 0.7.5, can you please verify?

**Comment by swederik** [comment]
Yep it's fixed.

Unfortunately, I still have an issue with the rendering of tools in cases where there are non-square pixels. Note the abnormal thickness of the reference line. Normal circular handles also become weird elongated ellipses. Now I know this is the 'correct' way to be drawing them, but it looks quite strange. I assume the same happens to text as well.

I guess this is because the drawing functions use setToPixelCoordinateSystem to make sure they end up in the right place.

Not too sure what to do about this. Maybe we can avoid doing the pixelSpacing scaling (https://github.com/chafey/cornerstone/blob/fbe7d530e906f87562e55a911f45e8c43652f7a5/src/setToPixelCoordinateSystem.js#L38) before drawing tools and apply some further translations to make sure the location is correct?

![screenshot 2015-06-01 15 38 19](https://cloud.githubusercontent.com/assets/607793/7914007/48aa8b1e-0874-11e5-837e-93412eeac337.png)

![screenshot 2015-06-01 15 31 11](https://cloud.githubusercontent.com/assets/607793/7913862/5a17a306-0873-11e5-8f4c-4be37c5e019d.png)

**Comment by chafey** [comment]
Fixing this will require that we move away from rendering overlays with canvas calls directly in the pixel coordinate system (which was really convenient!) and instead leave the canvas transformation matrix identity and convert from pixel coordinates to identity canvas coordinates via a transformation matrix.  I coded this up on the plane today and have it working, just need another hour or two to wrap it up.

**Comment by chafey** [comment]
OK just checked in the new transformation matrix code.  Instead of using setToPixelCoordinateSystem() and drawing directly with canvas, you can set the canvas to identity transform using       context.setTransform(1, 0, 0, 1, 0, 0); and then pixel coordinates to the canvas coordinates using pixelToCanvas() call.  This will likely be the recommended design going forward and the old way will be deprecated to prevent others from running into this issue.  Check out the nonSquarePixels example to see this in action and let me know what you think

So much for vacation today lol

**Comment by chafey** [comment]
@swederik have you had a chance to look at this yet?

**Comment by swederik** [comment]
Ah no not yet I didn't notice your last comment that you had committed the fix. I'll take a look

**Comment by chafey** [comment]
FYI - The pixelToCanvas() approach is working, this will be our recommended go forward strategy.  Leaving this open until cornerstoneTools has been update and all related docs

**Comment by chafey** [comment]
Erik - did we finish cleaning this up in cornerstoneTools yet?  Would like to close this...

**Comment by swederik** [comment]
Yeah all the tools have been using pixelToCanvas for a long time, but I don't think we got around to updating the Wiki yet.
